### ISSUE TITLE
Unable to run on OSX

### ISSUE THREAD

**Issue by cbzehner** [adamdehaven/change-git-author#1]
This is really nice but it doesn't seem to work for me? I'm on the latest OSX version using `bash` locally for my shell. Nothing fancy going on.

However when I run the script I see a couple different errors depending on _how_ I choose to run it. I'm not a bash expert so I may be overlooking something here. 😁 

I confirmed it's marked as executable
```bash
repo on  master [$?] via ⬢ v10.18.1 
❯ ls -l
total 1104
-rw-r--r--     1 cbzehner  staff    2514 Nov 10 21:19 README.md
-rwxr-xr-x     1 cbzehner  staff   17805 Nov 10 22:04 changeauthor.sh
```

Just trying to run it as expected
```bash
repo on  master [$?] via ⬢ v10.18.1 
❯ ./changeauthor.sh -o old@test.com -e new@test.com
: No such file or directory
```

Calling it with `bash` directly gives a different error
```bash
repo on  master [$?] via ⬢ v10.18.1 took 2s 
❯ bash changeauthor.sh 
: command not foundne 2: 
: command not foundne 9: 
: command not foundne 11: 
: command not foundne 24: 
: command not foundne 31: 
: command not foundne 34: 
: command not foundne 36: 
'hangeauthor.sh: line 43: syntax error near unexpected token `in
'hangeauthor.sh: line 43: `  case "$1" in
```

**Comment by adamdehaven** [comment]
@cbzehner thanks for pointing this out! I mistakenly changed the line endings the other day on my Windows machine. It should now run fine on Mac or Windows. I'd recommend deleting your local copy of the repository, and then grab a fresh copy. Let me know here if you have any issues and I'll reopen this issue to take a look.

You may need to run this before downloading a new copy in order to configure Git to ensure line endings in files you checkout are correct for OS X

``` sh
git config --global core.autocrlf input
```

**Comment by cbzehner** [comment]
Thanks for the quick response. I just ran it locally and it worked great.

This script is a much nicer experience than in the past when I've manually run the commands after looking them up on StackOverflow! 🎉
